### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xgssgss** [jellyCodee/Covid19-Prediction#1]
#from pretty_confusion_matrix import pp_matrix_from_data 
请问没有这个模块应当如何处理 # #

**Comment by sabiah-io** [comment]
Here is a link to the module's GitHub. It is well documented so it should be easy to use.

https://github.com/wcipriano/pretty-print-confusion-matrix

But if you don't want to/or can't install it you can use ScikitLearn's plot_confusion_matrix method from metrics.
